version: '3'

services:
  node:
    build: .
    env_file: .env
    ports:
      - "82:3000"
    volumes:
      - ./app:/home/node/app
      - /home/node/app/node_modules

  db:
    image: mariadb
    restart: always
    env_file: .env
    volumes:
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data: